#
# Deployment of the azarus challenge & token contracts
#
#
env: dev
nodeos_endpoint: "http://127.0.0.1:7777"
wallet:
  #type: keosd
  #url: "http://127.0.0.1:5555"
  type: file
  keys:
    eosio:
      private: 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
    master:
    user:
    oracle:
 
accounts:
  useraccnt:
    reset: true
    permissions:
      owner: 
        type: key
        value: master
      active:
        type: key
        value: master
        parent: owner
      user:
        type: key
        value: user
        parent: active
  oracleaccnt:
    reset: true #if true will overwrite permissions even if account already exists
    permissions:
    # permission_name:
    #   type: key or account
    #   value: if key - must be defined in wallet
    # permissions must be listed in hierarchical order
      owner: 
        type: key
        value: master
      active:
        type: key
        value: master
        parent: owner
      oracle: 
        type: key
        value: oracle
        parent: active
        authorize:
          - hello::hi
      user:
        type: account
        value: useraccnt@user
        parent: active
  helloaccnt:
    reset: true
    permissions:
      owner: 
        type: key
        value: master
      active:
        type: key
        value: master
        parent: owner

contracts:
  hello:
    upgrade: true
    contract_name: hello
    account: helloaccnt
    permission: owner
    post_actions: ~
    # js calls to setup contract
    verify_actions: ~
    # js calls to verify contract

test: ~